name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-audit
        run: cargo install --locked cargo-audit
      - name: Ensure optional features (pkcs11) are present in lockfile
        run: cargo build --workspace --features "pkcs11 pkcs11-backend" --quiet
      - name: Run cargo audit (blocking)
        run: cargo audit
