name: Clippy Lint

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  clippy:
    if: false
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
=======
        with:
          fetch-depth: 0
>>>>>>> be35db3d094cb6edd3c63585f33fdcb299a57158
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
