name: Merge Conflict Check

on:
  pull_request:
    branches: [ main ]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git identity for merge check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Check for merge conflicts
        continue-on-error: true
        run: |
          set -e
          git fetch origin main
          # Try normal merge first
          if git merge --no-commit --no-ff origin/main; then
            echo "merge check OK"
            git merge --abort
            exit 0
          fi
          echo "Attempting with --allow-unrelated-histories"
          if git merge --no-commit --no-ff --allow-unrelated-histories origin/main; then
            echo "merge (allow-unrelated-histories) succeeded; aborting"
            git merge --abort
            exit 0
          fi
          echo '::error ::Merge conflict detected with main branch.'
          exit 1
