name: No Print Macros Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for println!/eprintln!/dbg!
        run: |
          set -euo pipefail
          files=$(git ls-files '*.rs' | grep -v '^tests/' | grep -v '^.github/' || true)
          if [ -n "$files" ]; then
            if grep -nE "\bprintln!|\beprintln!|\bdbg!\(" $files; then
              echo "Found print macros in non-test code."
              exit 1
            fi
          fi
