name: Rust CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  fmt:
    if: false
    name: Rustfmt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
=======
        with:
          fetch-depth: 0
>>>>>>> be35db3d094cb6edd3c63585f33fdcb299a57158
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Check code format
        run: cargo fmt --all -- --check
