name: Secret Return Check

on:
  push:
    branches: [ main, master, archive-bridge-stub ]
  pull_request:
    branches: [ main, master, archive-bridge-stub ]
  workflow_dispatch:

jobs:
  check-secret-returns:
    name: Check public secret returns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run secret-return scan
        run: |
          python scripts/check_secret_returns.py
        shell: bash
