name: Security & Quality

on:
  push:
    branches: [ main, master, archive-bridge-stub ]
  pull_request:
    branches: [ main, master, archive-bridge-stub ]

jobs:
  fmt-clippy-test-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Run formatting check
        run: |
          rustup component add rustfmt || true
          cargo fmt --all -- --check

      - name: Run clippy
        run: |
          rustup component add clippy || true
          cargo clippy --all-targets --features test-env -- -D warnings

      - name: Run tests
        env:
          RUSTFLAGS: "-D dead_code"
        run: |
          cargo test --features test-env --workspace --quiet

      - name: Run cargo-audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run secret/print scan
        run: |
          chmod +x .github/scripts/scan_repo_for_secrets.sh
          .github/scripts/scan_repo_for_secrets.sh
