name: Lint (Non-Rust)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super Linter (docs & configs only)
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Only enable YAML explicitly; leave others unset when VALIDATE_ALL_CODEBASE=false
          VALIDATE_YAML: true
          # Exclude third-party and build outputs from lint scope
          FILTER_REGEX_EXCLUDE: '(^vendor/)|(^target/)|(^defi-target/)|(^\.vscode/)|(^patches/)'
          # Optionally enable others: VALIDATE_DOCKERFILE, VALIDATE_SHELL_SH
