name: Lint (Non-Rust)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super Linter (docs & configs only)
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable Rust checks here (covered by rust-ci.yml)
          VALIDATE_RUST: false
          # Keep common docs & config linters
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_GITHUB_ACTIONS: true
          # Exclude third-party and build outputs from lint scope
          FILTER_REGEX_EXCLUDE: '(^vendor/)|(^target/)|(^defi-target/)|(^\.vscode/)'
          # Optionally enable others: VALIDATE_DOCKERFILE, VALIDATE_SHELL_SH
